name: Build and push substrate ci image
on:
  push:
    branches:
      - bn128
  pull_request:

jobs:
  build-push-substrate-ci-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.1.0
      - run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          img_tag=$(git rev-parse --short "$GITHUB_SHA")
          docker buildx build --provenance=false --platform linux/amd64 -t ghcr.io/${GITHUB_REPOSITORY}:${img_tag} --push .
